### ISSUE TITLE
Self-signed certificate

### ISSUE THREAD

**Issue by arnold-bernstein** [scottyzen/woonuxt#124]
Hello I am running a wordpress installation in my local network behind an nginx reverse proxy with a self-signed ssl certificate. However the installation of woonuxt is throwing some error. Is it possible to use self-signed certs?

```bash
npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm WARN deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
npm WARN deprecated ohmyfetch@0.4.21: Package renamed to https://github.com/unjs/ofetch

> postinstall
> nuxi prepare

[4:20:55 PM] Error fetching woonuxt settings. Make sure you have the latest version woonuxt-settings plugin installed and activated WordPress. You can download it from https://github.com/scottyzen/woonuxt-settings

 ERROR                                                                                                                                                                                   4:20:56 PM
        Failed to load schema from https://intern_host:9091/graphql:

        self-signed certificate
        Error: self-signed certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1659:34)
    at TLSSocket.emit (node:events:517:28)
    at TLSSocket._finishInit (node:_tls_wrap:1070:8)
    at ssl.onhandshakedone (node:_tls_wrap:856:12)

        GraphQL Code Generator supports:
          - ES Modules and CommonJS exports (export as default or named export "schema")
          - Introspection JSON File
          - URL of GraphQL endpoint
          - Multiple files with type definitions (glob expression)
          - String in config file

        Try to use one of above options and run codegen again.

      

  Failed to load schema from https://intern_host:9091/graphql:
  
  self-signed certificate
  Error: self-signed certificate
  at TLSSocket.onConnectSecure (node:_tls_wrap:1659:34)
  at TLSSocket.emit (node:events:517:28)
  at TLSSocket._finishInit (node:_tls_wrap:1070:8)
  at ssl.onhandshakedone (node:_tls_wrap:856:12)
  
  GraphQL Code Generator supports:
  - ES Modules and CommonJS exports (export as default or named export "schema")
  - Introspection JSON File
  - URL of GraphQL endpoint
  - Multiple files with type definitions (glob expression)
  - String in config file
  
  Try to use one of above options and run codegen again.
  
  
  at executeCodegen (node_modules/@graphql-codegen/cli/esm/codegen.js:330:24)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async generate (node_modules/@graphql-codegen/cli/esm/generate-and-save.js:99:25)
  at async generate (node_modules/nuxt-graphql-client/dist/module.mjs:64:10)
  at async generateGqlTypes (node_modules/nuxt-graphql-client/dist/module.mjs:339:46)
  at async setup (node_modules/nuxt-graphql-client/dist/module.mjs:433:5)
  at async normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:2112:17)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2415:95)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:3858:7)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:3956:5)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2570:19)
  at async Object.run (node_modules/nuxi/dist/chunks/prepare.mjs:56:18)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1648:16)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1639:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1773:7)
  
  Error:
  Failed to load schema from https://intern_host:9091/graphql:
  
  self-signed certificate
  Error: self-signed certificate
  at TLSSocket.onConnectSecure (node:_tls_wrap:1659:34)
  at TLSSocket.emit (node:events:517:28)
  at TLSSocket._finishInit (node:_tls_wrap:1070:8)
  at ssl.onhandshakedone (node:_tls_wrap:856:12)
  
  GraphQL Code Generator supports:
  - ES Modules and CommonJS exports (export as default or named export "schema")
  - Introspection JSON File
  - URL of GraphQL endpoint
  - Multiple files with type definitions (glob expression)
  - String in config f
```

**Comment by AndreasMueck** [comment]
A solution for local development is to disable temporarly the certificate verification:

In your terminal (macOS / Linux) set:

`export NODE_TLS_REJECT_UNAUTHORIZED=0`

In [Windows](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/set_1)

**Comment by scottyzen** [comment]
## Add SSL support for local development with a self-signed certificate

Self-signed certificate #124
- Add SSL support for local development.
- Update README.md to include instructions for setting it up. You can find the instructions [here](https://github.com/scottyzen/woonuxt?tab=readme-ov-file#local-ssl-setup).
- Tested this setup with [Local](https://localwp.com/) by Flywheel.

**Comment by tzhf** [comment]
Hi there,
I'm running wordpress with Local, but despite the new SSL instructions, after a successfull `mkcert -install`, and a `npm run dev:ssl`, i'm still getting issues with SSL.
![image](https://github.com/user-attachments/assets/e322a2da-eb1c-491b-a8e8-b74180422d2c)

So my guess is that the local wordpress graphql endpoint must be SSL as well, so i modified the .env to `GQL_HOST="https://wordpress.local/graphql"`

But now i'm getting the exact same issue from @arnold-bernstein 
![image](https://github.com/user-attachments/assets/344fe17b-3760-4436-81a1-ee8d444edaa5)

It's probably me missing something
