### ISSUE TITLE
Routing in node is too restrictive

### ISSUE THREAD

**Issue by arnold-bernstein** [scottyzen/woonuxt#125]
Hey, 

I have been trying out a few other things and found that the routing in node.js backend might be too restrictive. It seems the application wants to use ipv6. In addition, the woonuxt-settings plugin is installed but not recognized by the frontend.

I expose the endopoint via 9090

From trying to connect to my wp backend on localhost I recieve the following error:

```bash
11:30:09 AM] Error fetching woonuxt settings. Make sure you have the latest version woonuxt-settings plugin installed and activated WordPress. You can download it from https://github.com/scottyzen/woonuxt-settings

 ERROR  Cannot start nuxt:                                                                                                                                                              11:30:10 AM
        Failed to load schema from http://localhost:9090/graphql:

        connect ECONNREFUSED ::1:9090
        Error: connect ECONNREFUSED ::1:9090
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at __node_internal_exceptionWithHostPort (node:internal/errors:671:12)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1549:16)

        GraphQL Code Generator supports:
          - ES Modules and CommonJS exports (export as default or named export "schema")
          - Introspection JSON File
          - URL of GraphQL endpoint
          - Multiple files with type definitions (glob expression)
          - String in config file

        Try to use one of above options and run codegen again.

      

  Failed to load schema from http://localhost:9090/graphql:
  
  connect ECONNREFUSED ::1:9090
  Error: connect ECONNREFUSED ::1:9090
  at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
  at __node_internal_exceptionWithHostPort (node:internal/errors:671:12)
  at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1549:16)
  
  GraphQL Code Generator supports:
  - ES Modules and CommonJS exports (export as default or named export "schema")
  - Introspection JSON File
  - URL of GraphQL endpoint
  - Multiple files with type definitions (glob expression)
  - String in config file
  
  Try to use one of above options and run codegen again.
  
  
  at executeCodegen (node_modules/@graphql-codegen/cli/esm/codegen.js:330:24)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async generate (node_modules/@graphql-codegen/cli/esm/generate-and-save.js:99:25)
  at async generate (node_modules/nuxt-graphql-client/dist/module.mjs:64:10)
  at async generateGqlTypes (node_modules/nuxt-graphql-client/dist/module.mjs:339:46)
  at async setup (node_modules/nuxt-graphql-client/dist/module.mjs:433:5)
  at async normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:2112:17)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2415:95)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:3858:7)
  at async NuxtDevServer._load (node_modules/nuxi/dist/chunks/dev2.mjs:253:5)
  
  Error:
  Failed to load schema from http://localhost:9090/graphql:
  
  connect ECONNREFUSED ::1:9090
  Error: connect ECONNREFUSED ::1:9090
  at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
  at __node_internal_exceptionWithHostPort (node:internal/errors:671:12)
  at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1549:16)
  
  GraphQL Code Generator supports:
  - ES Modules and CommonJS exports (export as default or named export "schema")
  - Introspection JSON File
  - URL of GraphQL endpoint
  - Multiple files with type definitions (glob expression)
  - String in config file
  
  Try to use one of above options and run codegen again.
  
  
  at loadSchema (node_modules/@graphql-codegen/cli/esm/load.js:42:15)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async node_modules/@graphql-codegen/cli/esm/codegen.js:186:69
  at async node_modules/@graphql-codegen/cli/esm/codegen.js:185:56
  at async node_modules/@graphql-codegen/cli/esm/codegen.js:62:17
  at async Task.run (node_modules/listr2/dist/index.js:960:11)
  at async node_modules/p-map/index.js:57:22
```

**Comment by scottyzen** [comment]
Hi @arnold-bernstein, you're most likely seeing this error be you don't have Enable Public Introspection turned on. You can find that option in the WPGrapghQL settings.

**Comment by arnold-bernstein** [comment]
Thanks, I will try it. In the meantime using 127.0.0.1 instead of localhost also works
