### ISSUE TITLE
Error 0: Cannot query field "loginWithCookies" on type "RootMutation".

### ISSUE THREAD

**Issue by RajaSharmaIndia** [scottyzen/woonuxt#161]
GraphQL Document Validation failed with 2 errors;                                                                           
  Error 0: Cannot query field "loginWithCookies" on type "RootMutation".
    at K:/Project/WooNuxt/woonuxt_base/queries/login.gql:3:3

Error 1: Cannot query field "logout" on type "RootMutation".
    at K:/Project/WooNuxt/woonuxt_base/queries/logout.gql:2:3

  Error 0: Cannot query field "loginWithCookies" on type "RootMutation".
  at K:/Project/WooNuxt/woonuxt_base/queries/login.gql:3:3

  Error 1: Cannot query field "logout" on type "RootMutation".
  at K:/Project/WooNuxt/woonuxt_base/queries/logout.gql:2:3
  at executeCodegen (/K:/Project/WooNuxt/node_modules/@graphql-codegen/cli/esm/codegen.js:330:24)
  at async generate (/K:/Project/WooNuxt/node_modules/@graphql-codegen/cli/esm/generate-and-save.js:99:25)
  at async generate (/K:/Project/WooNuxt/node_modules/nuxt-graphql-client/dist/module.mjs:65:10)
  at async generateGqlTypes (/K:/Project/WooNuxt/node_modules/nuxt-graphql-client/dist/module.mjs:340:46)
  at async setup (/K:/Project/WooNuxt/node_modules/nuxt-graphql-client/dist/module.mjs:435:5)
  at async normalizedModule (/K:/Project/WooNuxt/node_modules/@nuxt/kit/dist/index.mjs:2112:17)
  at async installModule (/K:/Project/WooNuxt/node_modules/@nuxt/kit/dist/index.mjs:2415:95)
  at async initNuxt (/K:/Project/WooNuxt/node_modules/nuxt/dist/index.mjs:4233:7)
  at async loadNuxt (/K:/Project/WooNuxt/node_modules/nuxt/dist/index.mjs:4331:5)
  at async loadNuxt (/K:/Project/WooNuxt/node_modules/@nuxt/kit/dist/index.mjs:2570:19)

  Error: GraphQL Document Validation failed with 2 errors;
  Error 0: Cannot query field "loginWithCookies" on type "RootMutation".
  at K:/Project/WooNuxt/woonuxt_base/queries/login.gql:3:3

  Error 1: Cannot query field "logout" on type "RootMutation".
  at K:/Project/WooNuxt/woonuxt_base/queries/logout.gql:2:3
  at codegen (/K:/Project/WooNuxt/node_modules/@graphql-codegen/core/esm/codegen.js:79:19)
  at async process (/K:/Project/WooNuxt/node_modules/@graphql-codegen/cli/esm/codegen.js:284:60)
  at async Promise.all (index 0)
  at async /K:/Project/WooNuxt/node_modules/@graphql-codegen/cli/esm/codegen.js:296:41
  at async /K:/Project/WooNuxt/node_modules/@graphql-codegen/cli/esm/codegen.js:62:17
  at async Task.run (/K:/Project/WooNuxt/node_modules/listr2/dist/index.js:960:11)
  at async node_modules\p-map\index.js:57:22

 ERROR  GraphQL Document Validation failed with 2 errors;                                                                             
  Error 0: Cannot query field "loginWithCookies" on type "RootMutation".
    at K:/Project/WooNuxt/woonuxt_base/queries/login.gql:3:3

Error 1: Cannot query field "logout" on type "RootMutation".
    at K:/Project/WooNuxt/woonuxt_base/queries/logout.gql:2:3

**Comment by RajaSharmaIndia** [comment]
![Uploading Screenshot 2024-05-16 114857.png…]()
