### ISSUE TITLE
Error fetching woonuxt settings.

### ISSUE THREAD

**Issue by kirilldorozhynskyi** [scottyzen/woonuxt#17]
Hi,
I just installed WP + woocommerce  and configured woonuxt settings, but nuxt application does not see the plugin and says Error fetching woonuxt settings. Make sure you have the latest version of woonuxt-settings plugin installed and activated on your WordPress site. You can download it from https://github.com/scottyzen/woonuxt-settings
Where could be the problem?

In graphiql ide I see woonuxtSettings
<img width="1406" alt="Screenshot 2023-03-05 at 09 43 23" src="https://user-images.githubusercontent.com/75448126/222950675-ad062949-94b1-4d15-9aa1-f1923e2db296.png">
<img width="1224" alt="Screenshot 2023-03-05 at 09 43 44" src="https://user-images.githubusercontent.com/75448126/222950687-25e5f5c9-076d-4f3d-9d1a-3b49a1b54f23.png">
<img width="1444" alt="Screenshot 2023-03-05 at 09 43 59" src="https://user-images.githubusercontent.com/75448126/222950704-f0ef77fe-5332-40b9-a679-92c480aac988.png">

**Comment by scottyzen** [comment]
Hi @kirilldorozhynskyi. I think this might be something to do with your WordPress site. Are you running it locally? I tried to hit your endpoint and it doesn't exist.

**Comment by Zielgestalt** [comment]
I have a similar problem. Fresh WP (6.1.1) with WooCommerce (7.4.1). Both in German. 
Plugins: woonuxt, and the graphql plugins installed via woonuxt plugin. No payment gateway installed, because I don't need one.
2 Simple Products in a Category.
Enabled login and logout mutations.

When starting nuxt (npm run dev) I get errors:

```
Error fetching woonuxt settings. Make sure you have the latest version woonuxt-settings plugin installed and activated on your WordPress site. You can download it from https://github.com/scottyzen/woonuxt-settings

 ERROR  Cannot start nuxt:  GraphQL Document Validation failed with 2 errors;                                                                                                     16:32:36
  Error 0: Cannot query field "loginWithCookies" on type "RootMutation".
    at /Users/galli/dev/dbsc/sandbox/woonuxt/gql/mutations/login.gql:2:3

Error 1: Cannot query field "logout" on type "RootMutation".
    at /Users/galli/dev/dbsc/sandbox/woonuxt/gql/mutations/logout.gql:2:3

  Error 0: Cannot query field "loginWithCookies" on type "RootMutation".
  at gql/mutations/login.gql:2:3
  
  Error 1: Cannot query field "logout" on type "RootMutation".
  at gql/mutations/logout.gql:2:3
  at executeCodegen (node_modules/@graphql-codegen/cli/dist/shared/graphql-codegen-cli-nuxt.111a00cc.mjs:953:20)
  at async generate (node_modules/@graphql-codegen/cli/dist/shared/graphql-codegen-cli-nuxt.111a00cc.mjs:1254:23)
  at async generate (node_modules/nuxt-graphql-client/dist/module.mjs:62:10)
  at async generateGqlTypes (node_modules/nuxt-graphql-client/dist/module.mjs:335:46)
  at async setup (node_modules/nuxt-graphql-client/dist/module.mjs:429:5)
  at async normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:167:5)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:435:15)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:2253:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6804:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6865:5)
  
  Error: GraphQL Document Validation failed with 2 errors;
  Error 0: Cannot query field "loginWithCookies" on type "RootMutation".
  at gql/mutations/login.gql:2:3
  
  Error 1: Cannot query field "logout" on type "RootMutation".
  at gql/mutations/logout.gql:2:3
  at codegen (node_modules/@graphql-codegen/core/esm/codegen.js:69:19)
  at async process2 (node_modules/@graphql-codegen/cli/dist/shared/graphql-codegen-cli-nuxt.111a00cc.mjs:902:44)
  at async Promise.all (index 0)
  at async node_modules/@graphql-codegen/cli/dist/shared/graphql-codegen-cli-nuxt.111a00cc.mjs:915:27
  at async node_modules/@graphql-codegen/cli/dist/shared/graphql-codegen-cli-nuxt.111a00cc.mjs:682:11
  at async Task.run (node_modules/listr2/dist/index.js:960:11)
  at async node_modules/p-map/index.js:57:22

```

When I use the internal GraphQL IDE or Postman I get:

```
{
    "data": {
        "woonuxtSettings": {
            "primary_color": "#7f54b2",
            "logo": "",
            "publicIntrospectionEnabled": "off",
            "frontEndUrl": "http://localhost:3000",
            "domain": "localhost",
            "maxPrice": null,
            "productsPerPage": 24,
            "wooCommerceSettingsVersion": "1.0.30",
            "global_attributes": null,
            "stripeSettings": {
                "enabled": null,
                "testmode": null,
                "test_publishable_key": null,
                "publishable_key": null
            }
        }
    },
    "errors": [
        {
            "debugMessage": "Expected a value of type \"Int\" but received: 4.20",
            "message": "Internal server error",
            "extensions": {
                "category": "internal"
            },
            "locations": [
                {
                    "line": 8,
                    "column": 5
                }
            ],
            "path": [
                "woonuxtSettings",
                "maxPrice"
            ]
        }
    ],
    "extensions": {
        "debug": [
            {
                "type": "DUPLICATE_TYPE",
                "message": "You cannot register duplicate Types to the Schema. The Type 'woonuxtOptionsStripeSettings' already exists in the Schema. Make sure to give new Types a unique name.",
                "type_name": "woonuxtOptionsStripeSettings",
                "stack": [
                    "/var/www/html/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php:645",
                    "/var/www/html/wp-content/plugins/wp-graphql/access-functions.php:184",
                    "/var/www/html/wp-includes/class-wp-hook.php:308",
                    "/var/www/html/wp-includes/class-wp-hook.php:332",
                    "/var/www/html/wp-includes/plugin.php:517",
                    "/var/www/html/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php:556",
                    "/var/www/html/wp-includes/class-wp-hook.php:308",
                    "/var/www/html/wp-includes/class-wp-hook.php:332",
                    "/var/www/html/wp-includes/plugin.php:517",
                    "/var/www/html/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php:246",
                    "/var/www/html/wp-content/plugins/wp-graphql/src/Registry/SchemaRegistry.php:38",
                    "/var/www/html/wp-content/plugins/wp-graphql/src/WPGraphQL.php:794",
                    "/var/www/html/wp-content/plugins/wp-graphql/src/Request.php:157",
                    "/var/www/html/wp-content/plugins/wp-graphql/src/Router.php:465",
                    "/var/www/html/wp-content/plugins/wp-graphql/src/Router.php:275",
                    "/var/www/html/wp-includes/class-wp-hook.php:308",
                    "/var/www/html/wp-includes/class-wp-hook.php:332",
                    "/var/www/html/wp-includes/plugin.php:565",
                    "/var/www/html/wp-includes/class-wp.php:399",
                    "/var/www/html/wp-includes/class-wp.php:780",
                    "/var/www/html/wp-includes/functions.php:1332",
                    "/var/www/html/wp-blog-header.php:16",
                    "/var/www/html/index.php:17"
                ]
            }
        ],
        "queryAnalyzer": {
            "keys": "bba289b7307ddb3fc7d557fd58fcdb3a5c6acc6f4ced0eae7eea1df22f1310b2 graphql:Query operation:getWooNuxtSettings",
            "keysLength": 107,
            "keysCount": 3,
            "skippedKeys": "",
            "skippedKeysSize": 0,
            "skippedKeysCount": 0,
            "skippedTypes": []
        }
    }
}
```

**Comment by Zielgestalt** [comment]
Whe I leave out 'maxPrice' in the GraphQL query I can get rid of the error 'Expected a value of type \"Int\" but received: 4.20'. This might be related to German number formating. But the DUPLICATE_TYPE is still there. Even when I leave out the stripeSettings in the query.

**Comment by Zielgestalt** [comment]
The same thing happens on a live page, but with an older Wordpress. That's why I tried a fresh install. Here's the temp GraphQL-Endpoint for that: https://portal.dbbc-bayern.de/graphql558746651346

**Comment by Zielgestalt** [comment]
Sorry, I deleted my recent comment. I made a mistake in my env files. So I have a similar problem like @kirilldorozhynskyi , but with an older Wordpress Version. On a fresh install everything works as expected.

**Comment by joelpmonteiro** [comment]
I'm also having the same error to use this version of woonuxt.
Ps.: I'm running locally on my machine.

![image](https://user-images.githubusercontent.com/37256731/224528561-bc52bc22-c22b-48d2-8263-517d384a5f74.png)


code used in wpGraphQL for testing, and it always gives this error.

![Screenshot_4](https://user-images.githubusercontent.com/37256731/224528593-52b4ec9d-5546-4e92-b27f-fdadcfdbd7b1.png)


now if i access the address locally http://localhost/graphql
![Screenshot_5](https://user-images.githubusercontent.com/37256731/224528784-45f3b923-5496-41d8-a92c-4544e1bf1fa1.png)

**Comment by scottyzen** [comment]
The warning about the DUPLICATE_TYPE field is fixed now on the latest [WooNuxt-Settings](https://github.com/scottyzen/woonuxt-settings/releases/tag/1.0.32) plugin. 

All the other issues seem to be happening when running WordPress locally. I need to set up a local environment myself to get to the bottom of it. But just note that WooNuxt will always need a live backend to work.

**Comment by joelpmonteiro** [comment]
I'm going to do a test on a hosting I bought, then I'll come back here to confirm that part.
