### ISSUE TITLE
Cannot start nuxt:  GraphQL Document Validation failed with 4 errors

### ISSUE THREAD

**Issue by JeremDigi** [scottyzen/woonuxt#75]
Hello

Thank you for this inspiring project in Nuxt. I want to try this solution!

I'm in a local environment. I installed wordpress and the required extensions. I created some sample products.

But I still get these errors. `yarn dev`. Where could this come from?

Thanks 

 ```
ERROR  Cannot start nuxt:  GraphQL Document Validation failed with 4 errors;                                                                                  14:55:23
  Error 0: Cannot query field "date" on type "ProductUnion". Did you mean to use an inline fragment on "ContentNode", "Product", "ExternalProduct", "GroupProduct", or "ProductVariation"?
    at /front/woonuxt_base/queries/getProducts.gql:15:7

Error 1: Cannot query field "terms" on type "ProductUnion". Did you mean to use an inline fragment on "Product", "ExternalProduct", "GroupProduct", "SimpleProduct", or "UnsupportedProduct"?
    at /front/woonuxt_base/queries/getProducts.gql:20:7

Error 2: Cannot query field "productCategories" on type "ProductUnion". Did you mean to use an inline fragment on "Product", "ExternalProduct", "GroupProduct", "SimpleProduct", or "UnsupportedProduct"?
    at /front/woonuxt_base/queries/getProducts.gql:26:7

Error 3: Cannot query field "allowedCountryStates" on type "RootQuery". Did you mean "allowedCountries" or "countryStates"?
    at /front/woonuxt_base/queries/getStates.gql:2:3

  Error 0: Cannot query field "date" on type "ProductUnion". Did you mean to use an inline fragment on "ContentNode", "Product", "ExternalProduct", "GroupProduct", or "ProductVariation"?
  at woonuxt_base/queries/getProducts.gql:15:7

  Error 1: Cannot query field "terms" on type "ProductUnion". Did you mean to use an inline fragment on "Product", "ExternalProduct", "GroupProduct", "SimpleProduct", or "UnsupportedProduct"?
  at woonuxt_base/queries/getProducts.gql:20:7

  Error 2: Cannot query field "productCategories" on type "ProductUnion". Did you mean to use an inline fragment on "Product", "ExternalProduct", "GroupProduct", "SimpleProduct", or "UnsupportedProduct"?
  at woonuxt_base/queries/getProducts.gql:26:7

  Error 3: Cannot query field "allowedCountryStates" on type "RootQuery". Did you mean "allowedCountries" or "countryStates"?
  at woonuxt_base/queries/getStates.gql:2:3
  at executeCodegen (node_modules/@graphql-codegen/cli/esm/codegen.js:330:24)
  at async generate (node_modules/@graphql-codegen/cli/esm/generate-and-save.js:99:25)
  at async generate (node_modules/nuxt-graphql-client/dist/module.mjs:63:10)
  at async generateGqlTypes (node_modules/nuxt-graphql-client/dist/module.mjs:337:46)
  at async setup (node_modules/nuxt-graphql-client/dist/module.mjs:431:5)
  at async normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:2141:17)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2439:95)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:3653:7)
  at async NuxtDevServer._load (node_modules/nuxi/dist/chunks/dev2.mjs:255:5)
  at async NuxtDevServer.load (node_modules/nuxi/dist/chunks/dev2.mjs:187:7)
```

**Comment by JeremDigi** [comment]
My settings : 

<img width="1358" alt="Capture d’écran 2023-10-06 à 15 25 58" src="https://github.com/scottyzen/woonuxt/assets/33928345/bf5b3cf1-df66-48bc-9596-46a1bb0f62ae">
<img width="1363" alt="Capture d’écran 2023-10-06 à 15 26 06" src="https://github.com/scottyzen/woonuxt/assets/33928345/5d4dd01e-6689-473a-8104-c6e57f280391">
<img width="1362" alt="Capture d’écran 2023-10-06 à 15 26 14" src="https://github.com/scottyzen/woonuxt/assets/33928345/e59c8a46-33ac-4740-806c-de

<img width="1362" alt="Capture d’écran 2023-10-06 à 15 26 14" src="https://github.com/scottyzen/woonuxt/assets/33928345/d83bf914-ed16-4886-aefc-6daa7c5f642c">

<img width="1192" alt="Capture d’écran 2023-10-06 à 15 26 26" src="https://github.com/scottyzen/woonuxt/assets/33928345/63435851-ddbb-4e30-91af-a644f0bb6686">


<img width="1362" alt="Capture d’écran 2023-10-06 à 15 26 14" src="https://github.com/scottyzen/woonuxt/assets/33928345/42b91105-32e5-45ac-93cb-83f6c493b0cc">

**Comment by JeremDigi** [comment]
Hmmm…
Ok, Next time I will read better. I had installed version 0.18 of WooGraphQL but needed 0.15
